#+TITLE: API's and Common Types

Components must agree on the data types they use to exchange data.  These may be data types defined in a common programming language, or data interchange types encoded in, say, JSON or protofbufs.

All of these datatypes should be versioned and should be defined as part of the architecture.  Since they do not naturally belong to either collaborating component, they should be defined here.

API and format versions shall be ~<major>.<minor>~, where a change is major for APIs iff a client cannot use the new API without modifications, and for data iff a valid data representation under the old format has different semantics (or is invalid) under the new.
A change is minor iff it modifies the intended or actual interpretation of the API or format definition.

* APIs
** [[./transaction-submission][Transaction submission]]
** [[./event-log][Node/ledger event log]]
** [[./proving-server][Proving server REST API]]
** [[./hoarfrost][Hoarfrost Storage API and Data Layout]]
** [[./dapp-connector][DApp Connector]]
* Data Types
** [[./field-aligned-binary][Field-Aligned Binary (FAB)]]
** [[./onchain-runtime][On-chain Virtual Machine and Runtime]]
