@startuml Component diagram for Lace Browser Extension

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam defaultFontName Liberation Sans

title [Component] Lace Browser Extension

Person(user, "DApp User", "User of a Midnight DApp")

Container_Boundary(extension, "Lace Browser Extension"){
  Component(dappConnector, "Midnight DApp Connector", "JavaScript and Lace DApp Connector",  "receives usigned transactions from DApps")
  Component(walletUI, "Midnight Wallet UI", "JavaScript and Lace UI Lib", "exposes Midnight Wallet functionality to the user")
  Component(walletEngine, "Midnight Wallet Engine", "JavaScript and Lace Wallet Core", "provides the core functionality of Midnight Wallet")  
  Component(midnightCrypto, "Midnight Crypto", "JavaScript and WASM", "Provides Midnight-specific cryptography operations")

  Rel(walletEngine, walletUI, "Uses")
  Rel(dappConnector, walletEngine, "connects to")
  Rel(walletEngine, midnightCrypto, "signs transactions using")

  Rel(walletEngine, user, "confirms transactions with")
}

ContainerDb(storage, "Browser's Local Storage", "Web Storage and IndexedDB", "stores encrypted private keys, address book, etc.")

Container_Ext(spa, "DApp Single Page Application", "JavaScript with ReactJS", "Exposes DApp functionality to the user via their browser")

System_Ext(mempool, "Midnight Mempool", "Mempool for Midnight transactions")
System_Ext(indexer, "Midnight PubSub Indexer", "PubSub service for Midnight")

Rel(user, spa, "interacts with")
Rel(user, walletEngine, "has a wallet at")

Rel_R(spa, dappConnector, "submit signed transactions to")
Rel(spa, indexer, "subscribes for updates from")

Rel(walletEngine, mempool, "sends signed transactions to")
Rel_D(walletEngine, storage, "reads from and writes to")

' Layout fixes
Lay_R(spa, dappConnector)

@enduml
