@startuml
autonumber
hide footbox

'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

actor user

'Dapp might be embedded/"installed" inside wallet, but even then it requires quite strong separation between wallet and dApp code
box "dApp" #eef
        participant "client-sdk" as clientSdk
        participant "Transition\nFunction" as gamma
        database "Pending\nPrivate\nUpdates" as pending
end box


box "Wallet" #eff
    'The browser extension
    participant "Wallet" as wallet
    'Wallet Backend, server component that works as a cache for frontend + bridge between frontend and the network
    participant "Wallet Backend" as walletBackend
end box
/'
 ' box "Wallet Backend Component" #efe
 '         participant "WBE\nClient API" as walletBackend
 '         database "Client\nData" as clientData
 ' end box
 '/
box "Proof Server Component" #fee
        participant "Proof\nServer" as proofServer
end box

boundary Consensus as consensus

'==================================================================
        ' Wallet Backend is always active, at least from perspective of this flow
        activate walletBackend

        user -> clientSdk : action

        activate clientSdk
        group compute a state update
                clientSdk -> gamma : update(args) using\n  public state,\n  private state
                activate gamma
                        gamma -> clientSdk : ok(result,\n     private transcript,\n     public transcript,\n     witness,\n     gas estimate)
                deactivate gamma
        end

        clientSdk -> pending ++ : store pending private transcript
        return ok

        group build and send transaction
                clientSdk -> wallet : callTx(call, circuit, witness)
                activate wallet
                group over TLS, to TEE in Proof Server
                        note over wallet: witness includes private data\nnot shared with Wallet Backend
                        wallet -> proofServer : prove(circuit, witness)
                        activate proofServer
                                proofServer -> wallet : proof
                        deactivate proofServer
                end

                wallet -> walletBackend : submitTx(tx)
                walletBackend -> consensus : submitTx(tx)
                walletBackend -> wallet : pending
                wallet -> clientSdk : pending
        end

        clientSdk -> user: pending

        == time passes as TX is verified and propageted ==

        consensus -> walletBackend : verified tx and new public state
        walletBackend -> wallet : verified tx, new public state
        wallet -> clientSdk : tx verified, new public state

        deactivate wallet

        group dApp processes consesus data
                clientSdk -> clientSdk : install new public state
                clientSdk -> pending ++ : fetch private transcript for the tx
                pending -> clientSdk -- : private transcript for the tx
                clientSdk -> clientSdk : apply private transcript
                clientSdk -> clientSdk : install new private state
        end

        clientSdk -> user : outcome information
deactivate clientSdk


'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
