@startuml
autonumber
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

actor user

box "dApp" #eef
        participant dApp as dapp
        participant "Transition\nFunction" as gamma
        database "Pending\nPrivate\nUpdates" as pending
end box
box "Wallet Frontend" #efe
        participant "Wallet" as wallet
        database "Client\nData" as clientData
end box
box "Wallet Backend"
    participant "Wallet Backend" as walletBackend
end box
box "Proof Server Component" #fee
        participant "Proof\nServer" as proofServer
end box

boundary Consensus as consensus

'==================================================================


user -> dapp : action

activate dapp
        /'
        ' group sync public and private state
        '         note over dapp
        '                 The dApp attempts to work with the
        '                 most current view of the blockchain,
        '                 synchronizing via the Wallet Backend
        '         end note
        '         dapp -> walletBackend : sync
        '         activate walletBackend
        '                 walletBackend -> dapp : public state,\n⟨event ⊕ transaction, ...⟩
        '         deactivate walletBackend
        '         /\'
        '         ' rnote over dapp #eee
        '         '         dApp:
        '         '           - install public state
        '         '           - update private state from
        '         '                ⟨event ⊕ transaction, ...⟩
        '         ' end rnote
        '         '\/
        ' end
        '/


        group compute and store a state update
            dapp -> gamma : update(args) using\n  public state,\n  private state
            activate gamma
                    gamma -> dapp : ok(result,\n     new public state,\n     new private state,\n     private transcript,\n     public transcript,\n     witness)
            deactivate gamma

            group over TLS, to TEE in proof server
                note over dapp: witness includes private data\nnot shared with Wallet
                dapp -> proofServer : prove(circuit, witness)
                note over proofServer: omitting details of\nsession management
                activate proofServer
                        proofServer -> dapp : proof
                deactivate proofServer
            end

            dapp -> pending ++ : store pending private\ntranscript indexed by tx
            return ok
        end

        group build and send transaction
                dapp -> wallet : make call tx (call, transcripts)
                activate wallet
                group identify payment
                            wallet -> clientData ++ : fetch coins
                            clientData -> wallet : coins
                        deactivate clientData
                        wallet -> wallet : estimate cost, select coins
                end

                group obtain authorization
                        note over wallet : now we have all the data needed to ask user for authorization\nthough a 2-stage process may be better suited:\n - first dApp asks if can interact with wallet at all(and user confirms or rejects)\n - then wallet asks user for each separate transaction
                        note over wallet: alternative flow: user pre-authorizes to avoid this step. \nDepending on time it takes to calculate SC ZK-proofs (steps 4, 5) \nthe user experience may require moving user authorization step earlier
                        wallet -> user : request authorization\nof leakage report & coins
                        user -> wallet : authorized
                end

                note over wallet: Now perform the expensive spend\nproofs to complete the transaction.
                group over TLS, to TEE in proof server
                        wallet -> proofServer : prove spend
                        activate proofServer
                                proofServer -> wallet : spendProof
                        deactivate proofServer
                end

                wallet -> wallet : build tx 'call' using\n  contractId,\n  public transcript,\n  proof,\n  coins
                wallet -> clientData ++ : savePending(tx)
                clientData -> wallet -- : ok
                note over walletBackend : omitting details of initialization and session management
                wallet -> walletBackend : submitTx(tx)
                activate walletBackend
                        walletBackend -> consensus : submitTx(call, circuitId, proof, spendIns, spendOuts, spendProof)
                        walletBackend -> wallet : submitted
                wallet -> dapp : submitted
                deactivate wallet
        end

        dapp -> user: pending

        == time passes as TX is verified and propageted ==

deactivate dapp


note over user: possibly offline

group Wallet Backend observes consensus
        consensus -> walletBackend : verified tx and new public state
        walletBackend -> walletBackend : store for client
end

== time passes until Wallet Front End polls Back End or user opens browser ==

note over user: online

'activation doesn't seem to work here
activate wallet

group wallet processes consensus data
    wallet -> walletBackend : sync
    walletBackend -> wallet :  public state, tx
    wallet -> clientData ++ : public state, tx
    clientData -> wallet -- : ok
end

deactivate walletBackend

note over user: online, opens dApp
group dApp processes confirmed transaction
    activate dapp
        dapp -> wallet: refresh
        wallet -> dapp: public state, tx
        dapp -> dapp : install new public state
        dapp -> pending ++ : fetch private transcript
        pending -> dapp -- : private transcript
        dapp -> dapp : apply private transcript
        dapp -> dapp : install new private state
        dapp -> user : outcome information
    deactivate dapp
end


'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
