@startuml
autonumber
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

actor user

box "dApp" #eef
        participant "Midnight.js" as midnightjs
        participant "Transition\nFunction" as gamma
        database "Pending\nPrivate\nUpdates" as pending
end box
box "Wallet" #efe
        participant "Wallet" as wallet
        database "Client\nData" as clientData
end box
box "Services"
    participant "Indexer" as indexer
    participant "Proof\nServer" as proofServer
    participant "Midnight Node" as node
end box

boundary Consensus as consensus

'==================================================================


user -> midnightjs : action

activate midnightjs
        group compute and store a state update
            midnightjs -> gamma : call(args) using\n  public state,\n  private state
            activate gamma
                    gamma -> midnightjs : ok(result,\n     new public state,\n     new private state,\n     private transcript,\n     public transcript,\n     witness)
            deactivate gamma

            group to local Proof Server or over TLS to a remote, TEE-equipped one
                note over midnightjs: witness includes private data\nnot shared with Wallet
                midnightjs -> proofServer : prove(tx_outline(circuit, witness))
                note over proofServer: omitting details of\nsession management
                activate proofServer
                        proofServer -> midnightjs : proven transaction
                deactivate proofServer
            end

            midnightjs -> pending ++ : store pending private data indexed by tx
            return ok
        end

        group build and send transaction
            midnightjs -> wallet++ : balance tx (call, transcripts)

            group obtain authorization
                note over wallet : now we have all the data needed to ask user for authorization\nthough in practice0 2-stage process is usually in place:\n - first dApp asks if can interact with wallet at all(and user confirms or rejects)\n - then wallet asks user for each separate transaction
                note over wallet: alternative flow: user pre-authorizes to avoid this step. \nDepending on time it takes to calculate SC ZK-proofs (steps 4, 5) \nthe user experience may require moving user authorization step earlier
                wallet -> user : request authorization\nof leakage report & coins
                user -> wallet : authorized
            end

            group identify payment
                wallet -> clientData ++ : fetch coins
                return coins
                wallet -> wallet : estimate cost, select coins
            end

            note over wallet: Now perform the expensive spend\nproofs to complete the transaction.

            group to local Proof Server or over TLS to a remote, TEE-equipped one
                    wallet -> proofServer ++ : prove spend
                    return proven spend
            end

            wallet -> wallet : assemble tx 'call' from call tx and spend tx
            wallet -> clientData ++ : savePending(tx)
            return ok
            return tx

            midnightjs -> wallet ++ : submitTx(tx)

            wallet -> node ++ : submitTx(tx)
            node -> consensus : broadcastTx(tx)
            return ok

            return pending
            midnightjs -> user: pending
        end

deactivate midnightjs

== time passes as TX is verified and propageted ==

note over user: possibly offline

group Indexer observes consensus
        consensus -> indexer : verified tx and new public state
        indexer -> indexer : store for client
end

== time passes until Wallet Front End polls Indexer or user opens browser ==

note over user: online

group wallet processes consensus data

    wallet -> indexer : sync
    activate wallet
    indexer -> wallet :  tx, public state update
    wallet -> clientData ++ : tx, wallet state
    return ok
end

note over user: online, opens dApp
group dApp processes confirmed transaction
        midnightjs -> indexer++: query pending tx, public state
        activate midnightjs
        return public state, tx
        midnightjs -> midnightjs : install new public state
        midnightjs -> pending ++ : fetch private data
        return private data
        midnightjs -> midnightjs : apply private data
        midnightjs -> midnightjs : install new private state
        midnightjs -> user : outcome information
    deactivate midnightjs
end


'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
