@startuml
autonumber
hide footbox

'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

actor user

'Dapp might be embedded/"installed" inside wallet (or the other way around), but even then it requires quite strong separation between wallet and dApp code
box "dApp" #eef
        participant "Midnight.js" as midnightjs
        participant "Transition\nFunction" as gamma
        database "Pending\nPrivate\nUpdates" as pending
end box


box "Wallet" #eff
    'The browser extension
    participant "Wallet" as wallet
end box

box "Services" #fee
        participant "Proof\nServer" as proofServer

        'Indexer acts as a Wallet Backend - server component that works as a cache for frontend + bridge between frontend and the network
        participant "Indexer" as indexer

        participant "Midnight Node" as node
end box

box "Midnight Network"
  boundary Consensus as consensus
end box

'==================================================================
        ' Indexer is always active, at least from perspective of this flow
        activate indexer

        user -> midnightjs : action

        activate midnightjs
        group call a contract
                midnightjs -> gamma : call(args) using\n  public state,\n  private state
                activate gamma
                        gamma -> midnightjs : ok(result,\n     private transcript,\n     public transcript,\n     witness,\n     gas estimate)
                deactivate gamma
        end

        group to local Proof Server or over TLS to a remote, TEE-equipped one
                                note over midnightjs: witness includes private data\nnot shared with Wallet
                                midnightjs -> proofServer : prove(transaction_outline(circuit, witness))
                                activate proofServer
                                        proofServer -> midnightjs : proven transaction
                                deactivate proofServer
                        end

        midnightjs -> pending ++ : store pending data
        return ok


        group build and send transaction
                midnightjs -> wallet : balanceTransaction(tx)
                activate wallet
                group to local Proof Server or over TLS to a remote, TEE-equipped one
                        wallet -> proofServer : prove(balancing_tx_outline)
                        activate proofServer
                                proofServer -> wallet : proven balancing transaction
                        deactivate proofServer
                end

                wallet -> wallet : assemble aggregated transaction
                wallet -> midnightjs : ok(aggregated_transaction)

                midnightjs -> wallet : submitTx(tx)
                wallet -> node : submitTx(tx)
                node -> consensus : submitTx(tx)
                node -> wallet : ok
                wallet -> midnightjs : pending
        end

        midnightjs -> user: pending

        == time passes as TX is verified and propageted ==

        consensus -> indexer : verified tx and new public state
        indexer -> wallet : verified tx, public state updates
        wallet -> user : outcome information
        wallet -> midnightjs : tx verified

        deactivate wallet

        group dApp processes consesus data
                midnightjs -> indexer : fetch new public state
                indexer -> midnightjs : new public state
                midnightjs -> midnightjs : install new public state
                midnightjs -> pending ++ : fetch private data
                pending -> midnightjs -- : private data
                midnightjs -> midnightjs : install new private state
        end

        midnightjs -> user : outcome information
deactivate midnightjs


'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
