@startuml 
autonumber
hide footbox 
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

!include example-dapps/evoting/participants.puml

par
activate A
        A -> rho_a ++ : KeyGen
                hnote over rho_a #aqua
                        keys := ⟨pk[A],sk[A]⟩
                end note
        return pk[A]
deactivate A
else
        
activate B
        B -> rho_b ++ : KeyGen
                hnote over rho_b #aqua
                        keys := ⟨pk[B],sk[B]⟩
                end note
        return pk[B]
deactivate B
else

activate C
        C -> rho_c ++ : KeyGen
                hnote over rho_c #aqua
                        keys := ⟨pk[C],sk[C]⟩
                end note
        return pk[C]
deactivate C
end
'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------


@enduml
