@startuml
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------
skinparam BoxPadding 5
hide footbox
title Contract Interaction - Different Applications

participant "Authentication" as authentication
participant "Application A" as A
participant "Application B" as B
box "\nContract Kernel" #ddd
  participant "Kernel" as kernel
  database "Contract\nStore" as contracts
  participant "Authorization" as authorization
  participant "Runtime" as runtime
  participant "Proof Server" as proofServer
end box
box "\n  Contract [0x01]  " #eef
  participant "Transition\nFunction" as transFuncC
end box
box "\n  Contract [0x02]  " #fee
  participant "Transition\nFunction" as transFuncD
end box

== Installation ==

A -> kernel ++ : **install** (0x01, contract, access_policy)
  activate A
  kernel -> contracts ++ : **set** (0x01, contract)
  return //ack//
  kernel -> authorization ++ : **set** (0x01, access_policy)
  return //ack//
return //ack//
deactivate A

== Authentication ==

B -> authentication ++ : **authenticate** (context)
activate B
return //access_token//
deactivate B

== Invocation ==

B -> kernel ++ : **call** (access_token, 0x01, func, args)
activate B
kernel -> authorization ++ : **authorize** (access_token, 0x01)
return //authorized//
kernel -> runtime ++ : **execute** (access_token, 0x01, func, args)
activate kernel
runtime -> contracts ++ : **get** (0x01)
return //contract [0x01]//
runtime -> transFuncC ++ : **apply** (access_token, args)
...
transFuncC -> runtime ++ : **execute** (access_token, 0x02, func', args')
runtime -> authorization ++ : **authorize** (access_token, 0x02)
return //authorized//
runtime -> contracts ++ : **get** (0x02)
return //contract [0x02]//
runtime -> transFuncD ++ : **apply** (access_token, args')
...
return //publicTranscript, privateTranscript, result//
return //result//
...
return //publicTranscript', privateTranscript', result'//
return //publicTranscripts, privateTranscripts, results//
kernel -> proofServer ++: **prove** (publicTranscripts, privateTranscripts, results)
return // proof//
deactivate kernel
return //proof, result'//
deactivate B

'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
