@startuml Install Callback

skinparam SequenceMessageAlignment center

title

  Install Callback

end title

"Application" -> "Lares Backend" : installCallback(filter, callback)
"Lares Backend" -> "Filter Service" : installFilter(filter)
loop
  "Filter Service" -> "Lares Backend" : event
  opt verify(event)
    "Lares Backend" -> "Lares Backend" : callback(event)
  end
end
@enduml