@startuml Join Contract

skinparam SequenceMessageAlignment center

title

  Join Contract

end title

"Application" -> "Lares Backend" : join(address, filter, privateStateConstructor)
"Lares Backend" -> "Lares Backend" : events = []
"Lares Backend" -> "Filter Service" : installFilter(filter)
loop Until all events are sent
  "Filter Service" -> "Lares Backend" : event
  "Lares Backend" -> "Lares Backend" : events = append(event, events)
end
note right
The filter should specify when it no 
longer applies
end note
"Lares Backend" -> "Contract State Service" : getContract(address)
"Contract State Service" --> "Lares Backend" : contract
"Lares Backend" -> "Lares Backend": contract.privateState = privateStateConstructor(events)
"Lares Backend" -> "Contract Storage" : store(address, contract)
"Lares Backend" --> "Application" : end
"Lares Backend" -> "Filter Service" : installFilter(txsFor(address))
note right
Should only return transactions from 
blocks following the block corresponding 
to the previously returned state
end note
"Filter Service" --> "Lares Backend" : ack
loop Until unjoin
  "Filter Service" -> "Lares Backend" : tx
  "Lares Backend" -> "Lares Backend" : apply(tx)
end
@enduml