@startuml

header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n

footer \n\n\nCopyright %date("yyyy"), Input Output Global, Ltd.

actor User

component mnjs as "Midnight.JS"

component DaoDapp {
    interface DaoStateAPI as "Dao State API"

    component DappUI

    component Contract {
        component TypeScriptRunnable
        component zkKeys
    }

    component DAOFacade

    component DAOState

    DAOFacade -- DAOState
    DAOFacade -- Contract
    DAOFacade -- mnjs
    DappUI -- DAOFacade
    DappUI -- DaoStateAPI
    DaoStateAPI <|-- DAOState
}

component PubSub as "PubSub Indexer"
interface PubSubGQLAPI as "PubSub GraphQL API"

component Wallet {
    interface WalletAPI as "Wallet API"

    component WalletUI

    component WalletEngine

    WalletUI -- WalletAPI
    WalletAPI <|-- WalletEngine
}



component LedgerLibs {
  component CompactRuntime
  component Zswap
}

component Node {
    component NodeRPC

    component NodeLedger

    NodeRPC -- NodeLedger
}

component ZKIR

component Plonk

component Compactc

component LedgerADTs {
    component ADTInterface
    component ADTImplmentation
}

PubSubGQLAPI <|-- PubSub
PubSub -- NodeRPC

User -- DappUI
User -- WalletUI
mnjs -- PubSubGQLAPI
WalletEngine -- PubSubGQLAPI
WalletEngine -- Zswap
NodeLedger -- LedgerLibs
mnjs -- LedgerLibs
ZKIR -- Plonk
LedgerLibs -- Plonk
Contract .. Compactc : "is produced by"
Compactc -- ZKIR
LedgerLibs -- ZKIR
Compactc -- ADTInterface
ADTImplmentation -- LedgerLibs


@enduml
