@startuml

header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n

footer \n\n\nCopyright %date("yyyy"), Input Output Global, Ltd.

actor User

node UserComputer as "User Computer\n<<machine>>" {
    node UserBrowserTab as "User Browser Tab\n<<process>>" {
        component DApp as "DApp"
    }

    node WalletBrowserExtension as "Wallet Browser Extension\n<<process>>" {
      component DAppConnector as "DApp Connector"
    }

    node ProofServer as "Proof Server\n<<process>>" {
      component Plonk
    }

    DApp -- DAppConnector : "extension messaging API"
    DApp -- ProofServer
    WalletBrowserExtension -- ProofServer
}

node DAppServer as "DApp Server\n<<machine>>" {
    artifact DAppBundle as "DApp Bundle"

    node HttpServer as "DApp Http Server\n<<process>>"

    HttpServer -- DAppBundle : "hosts"
}

node ServiceHost as "Service Host\n<<machine>>" {
    node PubSubIndexer as "PubSub Indexer\n<<process>>"


    node NodeInstance as "Node\n<<process>>" {

    }

    PubSubIndexer -- NodeInstance
}

node BlockProducerHost as "Block Producer Host\n<<machine>>" {
  node BlockProducerNodeInstance as "Block Producer Node\n<<process>>"
}

cloud MidnightNetwork as "Midnight Network"

User -- UserBrowserTab
User -- WalletBrowserExtension
UserBrowserTab -- HttpServer
NodeInstance -- MidnightNetwork
UserBrowserTab -- PubSubIndexer
WalletBrowserExtension -- PubSubIndexer
WalletBrowserExtension -- NodeInstance
MidnightNetwork -- BlockProducerNodeInstance

@enduml
