@startuml
' left to right direction
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n

footer \n\n\nCopyright %date("yyyy"), Input Output Global, Ltd.

!function $instanceName($name) !return $name + "Instance"
!function $dappServerName($name) !return $name + "DapServer"
!function $uiName($name) !return $name + "DappUI"
!function $dappBackendName($name) !return $name + "DappBackend"
!function $dappKey($name) !return $name + "DappKey"
!function $wallet($name) !return $name + "Wallet"
!function $walletKey($name) !return $name + "WalletKey"
!function $walletEngine($name) !return $name + "WalletEngine"
!function $walletTUI($name) !return $name + "WalletTUI"
!function $actorDisplay($name, $isVoter)
    !if ($isVoter) 
        !$prefix ?= "Voter "
    !else 
        !$prefix ?= ""
    !endif
    !return $prefix + $name
!endfunction

node NodeHost as "Node Host\n<<machine>>" {
    artifact BootstrapFile

    component NodeInstance as "Node Instance\n<<process>>" {
        artifact NodeImplementation

        storage Ledger [
            LedgerState
            <<ephemeral>>
        ]
    }
}

!procedure $dappDeployment($name, $isVoter=false)
    actor :$actorDisplay($name, $isVoter): as $name
    node $instanceName($name) as "$name Instance\n<<machine>>" {
        artifact $dappKey($name) as "Dapp Secret Key"
        artifact $walletKey($name) as "Wallet Secret Key" 
        node $dappServerName($name) as "Dapp Server\n<<Node.js process>>" {
            ' component $uiName($name) as "Dapp UI\n<<hosted to browser>>"
            ' component $dappBackendName($name) as "Dapp Backend"
        }
        node $wallet($name) as "Wallet\n<<Node.js process>>" {
            ' component $walletEngine($name) as "Wallet Engine"
            ' component $walletTUI($name) as "Wallet TUI"
        }
    }

    $instanceName($name) --- NodeHost
    ' $dappServerName($name) ---- NodeInstance
    ' $actorName($name) -- $uiName($name)
    ' $actorName($name) -- $walletTUI($name)
    ' $wallet($name) -- NodeInstance
    $dappServerName($name) -- $wallet($name)
    $name -- $dappServerName($name)
    $name -- $wallet($name)
!endprocedure




' together {
    $dappDeployment("Alice", $isVoter=true)
    $dappDeployment("Bob", $isVoter=true)
    $dappDeployment("Charlie", $isVoter=true)
    $dappDeployment("Organizer")
' }


@enduml
