@startuml

header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n

footer \n\n\nCopyright %date("yyyy"), Input Output Global, Ltd.

state Private {
    state Organizer {
        state COrganizerCheck <<choice>>
        [*] --> COrganizerCheck : Observe Deploy
        COrganizerCheck --> ImOrganizer : public_key(local_secret_key) == ledger.organizer
        COrganizerCheck --> NotOrganizer : public_key(local_secret_key) != ledger.organizer
    }
    --
    state Voter {
        [*] --> VoterUnitialized : Deploy
        VoterUnitialized --> VoterUnitialized : Buy in voting tokens
        VoterUnitialized --> VoterCommitted : Commit vote\nrequires a voting token
        VoterCommitted --> VoterRevealed : Reveal vote
        VoterRevealed --> VoterUnitialized : Observe advance to initial
        VoterCommitted --> VoterUnitialized : Observe advance to initial
    }
    --
    state Beneficiary {
        state CBeneficiaryCheck <<choice>>

        [*] -d-> BeneficiaryUnitialized
        BeneficiaryUnitialized -d-> CBeneficiaryCheck : Observe proposal init
        CBeneficiaryCheck -d-> ImBeneficiary : public_coin_key == ledger.beneficiary
        CBeneficiaryCheck --> NotBeneficiary : public_coin_key != ledger.beneficiary
        ImBeneficiary -r-> BeneficiaryUnitialized : cash out
        ImBeneficiary -r-> BeneficiaryUnitialized : observe advance to initial
        NotBeneficiary -r-> BeneficiaryUnitialized : observe advance to initial
    }
}
Private : it consists of 3 independent components which affect available actions
Private : organizer depends on ledger.organizer field, which is set at deploy
Private : beneficiary depends on ledger.beneficiary field, which is set at proposal init
Private : voter - anyone can try to vote, because wallet holds voting tokens and DApp does not know about this

@enduml
