@startuml

skinparam componentStyle uml2
skinparam linetype ortho
title Contract Kernel - Component\n
[Authentication] as authentication
package "Application [A]" as appA {
    [Core] as coreA
}
package "Application [B]" as appB {
    [Core] as coreB
}
package "Contract Kernel" {
  [Authorization] as authorization
  [Kernel] as kernel
  [Runtime] as runtime
  [Proof Server] as proofServer
  database "Contract Store" as contractStore {
    package "Contract [0x02]" {
      component "Function [bar]" as transFunc2
    }
    package "Contract [0x01]" {
      component "Function [foo]" as transFunc1
    }
  }
  kernel ..> proofServer
  kernel ..> runtime
  kernel .left...> contractStore
  kernel .left.> authorization
}
coreA .up.> authentication
coreB .up.> authentication
coreA .down.> kernel
coreB .down.> kernel
@enduml