'ER diagrams documented here
'    https://plantuml.com/ie-diagram
@startuml

header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n

footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.

entity Account {
  * accountId : AccountId <<PK>>
  * auth : AuthorizationScheme
  --
  freshSnapshots : Seq<StateSnapshot> <<Memory>>
}

entity AccountRelevantBlock {
  * account : AccountId <<FK>>
  * block : BlockHash <<FK>>
}

entity ExecutedBlock {
  * hash : BlockHash <<PK>>
  * parent : BlockHash <<FK>>
  * transactionsOrder : Seq<TransactionHash> <<FK>>
}

entity Transaction {
  * hash : TransactionHash <<PK>>
  * contractId : ContractId
  * publicTranscript : PublicTranscript
  * signature : Signature
}

entity ExecutedTransaction {
  publicState : ContractPublicState
}

entity PendingTransaction {
  * ttl : TTL
}

entity RelevantTransactionFilter {
  * definition : FilterDefinition
}

entity StateSnapshot {
  hook : Either<BlockHash, Timestamp> <<FK>>
  account : AccountId <<FK>>
  derivedState: DerivedState
  relevantBlocks: Seq<BlockHash> <<FK>>
  pendingTransactions: Seq<TransactionHash> <<FK>>
  newEvents : AccountEvent
}

entity NodeConnectionPool {
  availableNodes : Seq<NodeAddress>
}

entity ActiveNodeConnection {
  address : NodeAddress
}

entity ClientConnection {
  * targetAccount : AccountId <<FK>>
}


RelevantTransactionFilter ||..o{ ExecutedTransaction : "accepts or rejects"

Account ||--|{ RelevantTransactionFilter

ExecutedBlock ||--o| ExecutedBlock : "is parent of"
ExecutedBlock ||--o{ ExecutedTransaction

AccountRelevantBlock }|--|| ExecutedBlock

StateSnapshot }|--|| Account
StateSnapshot }|--o{ AccountRelevantBlock
StateSnapshot }|--o{ PendingTransaction
StateSnapshot }|--|| ExecutedBlock
StateSnapshot ||--o| StateSnapshot : "evolution of"

ExecutedTransaction |o--|| Transaction

PendingTransaction |o--|| Transaction

Account }o--|| NodeConnectionPool
NodeConnectionPool ||--o{ ActiveNodeConnection : "manages"
ActiveNodeConnection }o..|{ ExecutedBlock : "streams"

ClientConnection }o--|| Account : "connects to"
ClientConnection }o..|{ StateSnapshot : "receives"

@enduml
