'ER diagrams documented here
'    https://plantuml.com/ie-diagram
@startuml
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

frame "Light Wallet 1" {
        [WalletClient1]
}
frame "Light Wallet 2" {
        [WalletClient2]
}
frame "Light Wallet 3" {
        [WalletClient3]
}


frame "Backend Server" {
        [WalletBackend] #aliceblue;line:blue;text:blue
        [Node]
}

[WalletClient1] .. [WalletBackend]
[WalletClient2] .. [WalletBackend]
[WalletClient3] .. [WalletBackend]


[WalletBackend] .. [Node]

'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------
@enduml

