@startuml

entity EncryptedPrivateKey {}
entity ViewingKey {

}
entity KeyStore {}
entity KeyChain {}
entity RelevantTxFilter {
  * filterDefinition: Definition
}
entity SyncBlock {}
entity SyncTransaction {}
entity RelevantTransaction {}
entity TransactionHistory {}
entity DAppConnection {}
entity WalletBackendConnection {}
entity StateSnapshot {
  * newEvents: WalletEvent
  * derivedState : DerivedState
  * knownAddresses: Address[]
  * balance: Balance
}
entity Wallet {
  * lastSnapshot: StateSnapshot
}

Wallet ||--|{ StateSnapshot
Wallet ||--|| KeyChain
Wallet ||--|{ RelevantTxFilter

StateSnapshot }|--|| TransactionHistory
StateSnapshot |o--|| StateSnapshot : previous

TransactionHistory }|--o{ RelevantTransaction

DAppConnection }o--o{ RelevantTransaction
SyncBlock }o--o| WalletBackendConnection
SyncTransaction ||--o| RelevantTransaction
SyncTransaction }|--|| SyncBlock


RelevantTxFilter ||--o| KeyChain
RelevantTxFilter ||--o{ SyncTransaction : accepts or rejects

KeyChain ||--|| ViewingKey : derives from private key
KeyChain ||--|| KeyStore
KeyStore ||--|| EncryptedPrivateKey
@enduml
