@startuml
skinparam componentStyle uml2
skinparam linetype ortho

title Interapplication Messaging - Component\n
[Authentication] as authentication

package "Application A" as appA {
  [Proof Server] as proofServerA
  [Core] as coreA
  [Runtime] as runtimeA
  database "Contract Store" as contractStoreA {
    package "Contract [0x01]" as contractA {
      [Transition Function] as transFunc1
    }
  }
  coreA ..> proofServerA
  coreA ..> contractStoreA
  coreA ..> runtimeA
}

package "Application B" as appB {
  [Proof Server] as proofServerB
  [Core] as coreB
  [Runtime] as runtimeB
  database "Contract Store" as contractStoreB {
    package "Contract [0x02]" as contractB {
      [Transition Function] as transFunc2
    }
  }
  coreB ..> proofServerB
  coreB .right.> contractStoreB
  coreB ..> runtimeB
}

coreA .up.> authentication
coreB .up.> authentication

package "Application Mesh" as appMesh {
  [Kernel] as kernel
  database "Application Registry" as appReg
  kernel ..> appReg
}

[Authorization] as authorization

coreA ..> kernel
coreB ..> kernel
kernel .up.> authorization

@enduml