@startuml "Flowlet Example"

'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------

actor User as user
box "[[http://plantuml.com{Optional tooltip} Server Component]]"
        control "Client\nHandler" as clientHandler
        entity Sessions as sessions
end box


user -> clientHandler : join(id)
clientHandler -> sessions : registerSession(id)
alt success
        rnote over sessions: added as session_id
        sessions -> clientHandler : Ok(session_id)
        clientHandler -> user : Joined(session_id)
else failure
        rnote over sessions: failed to add
        sessions -> clientHandler : Failed
        clientHandler -> user : FailedToJoin
end

'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------


@enduml