@startuml
skinparam titleFontSize 25

title Midnight.js Deployment Diagram

node "Client Device" <<device>> {
    component Browser <<EE>> {
        artifact DappConnector
        database "IndexedDB" as IDB
        component GUI
        artifact "Web Page" as WP {
        }
        artifact MidnightJS {
            artifact Contracts
            artifact WalletProvider <<client>>
            artifact PublicDataProvider <<client>>
            artifact PrivateStateProvider <<client>>
            artifact ZKConfigProvider <<client>>
            artifact NodeProvider <<client>>
            artifact ProofProvider <<client>>
        }
        node Extensions <<EE>> {
            component "Wallet" as LW {
            }
        }
        artifact Ledger
        artifact "Compact Runtime" as CR
        artifact "Impact VM" as IR
    }
    component "Proof Server" as PS {
    }
    artifact compactc {
    }
}

node Indexer <<device>>
node "Substrate Node" <<device>> as SN
node "Web Server" <<device>> as WS {
    folder "Prover Keys"
    folder "Verifier Keys"
    folder "ZKIRs"
    artifact "foo.js" as Contract
    artifact "witnesses.js" as Witnesses
    artifact "UI Components" as UC
}


Contract --> Witnesses
Contract --> CR
WP --> MidnightJS
Contracts -> PublicDataProvider
Contracts --> PrivateStateProvider
Contracts --> ZKConfigProvider
Contracts --> WalletProvider
Contracts --> NodeProvider
Contracts --> ProofProvider
Contracts --> Ledger
Contracts --> CR
CR --> IR
LW --> Indexer

Ledger --> IR
compactc -[dashed]-> Contract: produces
LW --> Ledger
NodeProvider --> DappConnector
WalletProvider --> DappConnector
DappConnector --> LW
PublicDataProvider --> Indexer
Indexer --> SN
SN --> Ledger
LW --> SN
PrivateStateProvider --> IDB
ProofProvider --> PS
ZKConfigProvider --> WS
GUI --> WP
WS -[dashed]-> WP: serves
@enduml
