@startuml
!pragma teoz true
'-----------------------------------------------------------
' Please include this standard header
header %filename()\n%date("yyyy.MM.dd' at 'HH:mm z")\n\n\n
'-----------------------------------------------------------
hide footbox
title Contract Kernel - Sequence\n

participant "Authentication" as authentication
participant "Application [A]" as A
participant "Application [B]" as B

box "\nContract Kernel" #ddd
  participant "Kernel" as kernel
  database "Contract\nStore" as contracts
  participant "Authorization" as authorization
  participant "Runtime" as runtime
  participant "Proof Server" as proofServer
  box "\n  Contract [0x01]  " #eef
    participant "Function [foo]" as foo
  end box
  box "\n  Contract [0x02]  " #fee
    participant "Function [bar]" as bar
  end box
end box

== Installation [0x02] ==

B -> kernel ++ : **install** (0x02, contract [0x02], access_policy)
  kernel -> contracts ++ : **set** (0x02, contract [0x02])
  return //ack//
  kernel -> authorization ++ : **set** (0x02, access_policy)
  return //ack//
return //ack//

== Installation [0x01] ==

A -> kernel ++ : **install** (0x01, contract [0x01], access_policy)
  kernel -> contracts ++ : **set** (0x01, contract [0x01])
  return //ack//
  kernel -> authorization ++ : **set** (0x01, access_policy)
  return //ack//
return //ack//

== Authentication [B] ==

B -> authentication ++ : **authenticate** (context)
return //access_token//

== Invocation [0x01.foo] ==

B -> kernel ++ : **call** (access_token, 0x01, foo, args)
kernel -> runtime ++ : **execute** (access_token, 0x01, foo, args)
runtime -> authorization ++ : **authorize** (access_token, 0x01, foo)
return //authorized//
runtime -> contracts ++ : **get** (0x01)
return //contract [0x01]//
runtime -> foo ++ : **apply** (access_token, args)
foo -> runtime ++ : **execute** (access_token, 0x02, bar, args')
runtime -> authorization ++ : **authorize** (access_token, 0x02, bar)
return //authorized//
runtime -> contracts ++ : **get** (0x02)
return //contract [0x02]//
runtime -> bar ++ : **apply** (access_token, args')
return //result//
return //  result//
return // result'//
return //publicTranscripts, privateTranscripts, results//
kernel -> proofServer ++: **prove** (publicTranscripts, privateTranscripts, results)
return // proof//
return //proof, result'//

'-----------------------------------------------------------
' Please include this standard footer
footer \n\n\nCopyright %date("yyyy"), Input Output Hong Kong, Ltd.
'-----------------------------------------------------------

@enduml
