@startuml
[-> "<latex>t_1</latex>" ++ : spawn
deactivate "<latex>t_1</latex>"
[-> "<latex>p_1</latex>" ++ : spawn
deactivate "<latex>p_1</latex>"
[-> "<latex>p_2</latex>" ++ : spawn
deactivate "<latex>p_2</latex>"
[-> "<latex>p_3</latex>" ++ : spawn
deactivate "<latex>p_3</latex>"
[-> "<latex>stopper_1</latex>" ++ : spawn
deactivate "<latex>stopper_1</latex>"
== "launch scheduler with 5 running actors" ==
"<latex>t_1</latex>" ->o "<latex>t_1</latex>" : 1. tick
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (1)
== "(2) broadcast [1]: (Epoch 1)" ==
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" ->o "<latex>t_1</latex>" : 3. tick
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (2)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (3)
== "(4) broadcast [1]: (Epoch 2)" ==
deactivate "<latex>t_1</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (2)
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (4)
== "(5) broadcast/me [4]: #signed<(Propose #block<2 () 61040624>) 424E3E6D>" ==
deactivate "<latex>p_3</latex>"
"<latex>t_1</latex>" ->o "<latex>t_1</latex>" : 6. tick
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (5)
== "(7) broadcast/me [4]: #signed<(Vote #block<2 () 61040624>) 7337F496>" ==
deactivate "<latex>p_3</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (2)
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (4)
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (5)
== "(8) broadcast/me [2]: #signed<(Vote #block<2 () 61040624>) 1255F43E>" ==
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (7)
note over "<latex>p_1</latex>": "252047 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_1</latex>": "1 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_1</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (2)
== "(9) broadcast/me [3]: #signed<(Propose #block<1 () 61040624>) D2F4244F>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (4)
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (5)
== "(10) broadcast/me [3]: #signed<(Vote #block<2 () 61040624>) 29A2D35E>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (7)
note over "<latex>p_2</latex>": "252047 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_2</latex>": "1 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (8)
note over "<latex>p_2</latex>": "63523 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_2</latex>": "2 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (9)
== "(11) broadcast/me [3]: #signed<(Vote #block<1 () 61040624>) 28020566>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (10)
note over "<latex>p_2</latex>": "23344 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_2</latex>": "3 votes for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_2</latex>": "quorum on epoch 2"
deactivate "<latex>p_2</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (8)
note over "<latex>p_1</latex>": "63523 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_1</latex>": "2 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (9)
== "(12) broadcast/me [2]: #signed<(Vote #block<1 () 61040624>) 2301D767>" ==
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (10)
note over "<latex>p_1</latex>": "23344 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_1</latex>": "3 votes for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_1</latex>": "quorum on epoch 2"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (11)
note over "<latex>p_1</latex>": "285164 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_1</latex>": "1 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_1</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (11)
note over "<latex>p_2</latex>": "285164 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_2</latex>": "1 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (12)
note over "<latex>p_2</latex>": "512631 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_2</latex>": "2 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_2</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (7)
note over "<latex>p_3</latex>": "252047 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_3</latex>": "1 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (8)
note over "<latex>p_3</latex>": "63523 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_3</latex>": "2 votes for #block-ext<#block<2 () 61040624>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (9)
== "(13) broadcast/me [4]: #signed<(Vote #block<1 () 61040624>) 50E3E157>" ==
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (10)
note over "<latex>p_3</latex>": "23344 signed vote for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_3</latex>": "3 votes for #block-ext<#block<2 () 61040624>>"
note over "<latex>p_3</latex>": "quorum on epoch 2"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (11)
note over "<latex>p_3</latex>": "285164 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_3</latex>": "1 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (12)
note over "<latex>p_3</latex>": "512631 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_3</latex>": "2 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (13)
note over "<latex>p_3</latex>": "676687 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_3</latex>": "3 votes for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_3</latex>": "quorum on epoch 1"
deactivate "<latex>p_3</latex>"
"<latex>stopper_1</latex>" ->o "<latex>stopper_1</latex>" : 14. stop
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (12)
note over "<latex>p_1</latex>": "512631 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_1</latex>": "2 votes for #block-ext<#block<1 () 61040624>>"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (13)
note over "<latex>p_1</latex>": "676687 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_1</latex>": "3 votes for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_1</latex>": "quorum on epoch 1"
deactivate "<latex>p_1</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (13)
note over "<latex>p_2</latex>": "676687 signed vote for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_2</latex>": "3 votes for #block-ext<#block<1 () 61040624>>"
note over "<latex>p_2</latex>": "quorum on epoch 1"
deactivate "<latex>p_2</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (4)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (5)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (6)
== "(15) broadcast [1]: (Epoch 3)" ==
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (7)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (8)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (9)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (10)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (11)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (12)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (13)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" ->o "<latex>t_1</latex>" : 16. tick
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (15)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (16)
== "(17) broadcast [1]: (Epoch 4)" ==
deactivate "<latex>t_1</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (15)
== "(18) broadcast/me [3]: #signed<(Propose #block<3 () 3A2F39A7>) 0424E2B4>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (17)
== "(19) broadcast/me [3]: #signed<(Propose #block<4 () D4240717>) 3C36F2D1>" ==
deactivate "<latex>p_2</latex>"
"<latex>t_1</latex>" ->o "<latex>t_1</latex>" : 20. tick
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (15)
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (17)
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (18)
== "(21) broadcast/me [4]: #signed<(Vote #block<3 () 3A2F39A7>) E67286C4>" ==
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (19)
== "(22) broadcast/me [4]: #signed<(Vote #block<4 () D4240717>) E2F97F7C>" ==
deactivate "<latex>p_3</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (18)
== "(23) broadcast/me [3]: #signed<(Vote #block<3 () 3A2F39A7>) 1D27722B>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (19)
== "(24) broadcast/me [3]: #signed<(Vote #block<4 () D4240717>) 26B5E665>" ==
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (21)
note over "<latex>p_2</latex>": "770959 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_2</latex>": "1 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (22)
note over "<latex>p_2</latex>": "533499 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_2</latex>": "1 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_2</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (21)
note over "<latex>p_3</latex>": "770959 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_3</latex>": "1 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (22)
note over "<latex>p_3</latex>": "533499 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_3</latex>": "1 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (23)
note over "<latex>p_3</latex>": "965496 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_3</latex>": "2 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (24)
note over "<latex>p_3</latex>": "733196 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_3</latex>": "2 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_3</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (15)
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (17)
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (18)
== "(25) broadcast/me [2]: #signed<(Vote #block<3 () 3A2F39A7>) 6B7A385E>" ==
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (19)
== "(26) broadcast/me [2]: #signed<(Vote #block<4 () D4240717>) 72661753>" ==
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (21)
note over "<latex>p_1</latex>": "770959 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_1</latex>": "1 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (22)
note over "<latex>p_1</latex>": "533499 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_1</latex>": "1 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (23)
note over "<latex>p_1</latex>": "965496 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_1</latex>": "2 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (24)
note over "<latex>p_1</latex>": "733196 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_1</latex>": "2 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_1</latex>"
"<latex>stopper_1</latex>" -> "<latex>stopper_1</latex>" ++: **deliver** (14)
== "(27) broadcast [5]: (Stop)" ==
destroy "<latex>stopper_1</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (23)
note over "<latex>p_2</latex>": "965496 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_2</latex>": "2 votes for #block-ext<#block<3 () 3A2F39A7>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (24)
note over "<latex>p_2</latex>": "733196 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_2</latex>": "2 votes for #block-ext<#block<4 () D4240717>>"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (25)
note over "<latex>p_2</latex>": "734168 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_2</latex>": "3 votes for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_2</latex>": "quorum on epoch 3"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (26)
note over "<latex>p_2</latex>": "612426 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_2</latex>": "3 votes for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_2</latex>": "quorum on epoch 4"
deactivate "<latex>p_2</latex>"
"<latex>p_2</latex>" -> "<latex>p_2</latex>" ++: **deliver** (27)
destroy "<latex>p_2</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (25)
note over "<latex>p_1</latex>": "734168 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_1</latex>": "3 votes for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_1</latex>": "quorum on epoch 3"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (26)
note over "<latex>p_1</latex>": "612426 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_1</latex>": "3 votes for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_1</latex>": "quorum on epoch 4"
deactivate "<latex>p_1</latex>"
"<latex>p_1</latex>" -> "<latex>p_1</latex>" ++: **deliver** (27)
destroy "<latex>p_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (17)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (18)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (19)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (20)
== "(28) broadcast [1]: (Epoch 5)" ==
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (21)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (22)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (23)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (24)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (25)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (26)
deactivate "<latex>t_1</latex>"
"<latex>t_1</latex>" -> "<latex>t_1</latex>" ++: **deliver** (27)
destroy "<latex>t_1</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (25)
note over "<latex>p_3</latex>": "734168 signed vote for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_3</latex>": "3 votes for #block-ext<#block<3 () 3A2F39A7>>"
note over "<latex>p_3</latex>": "quorum on epoch 3"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (26)
note over "<latex>p_3</latex>": "612426 signed vote for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_3</latex>": "3 votes for #block-ext<#block<4 () D4240717>>"
note over "<latex>p_3</latex>": "quorum on epoch 4"
deactivate "<latex>p_3</latex>"
"<latex>p_3</latex>" -> "<latex>p_3</latex>" ++: **deliver** (27)
destroy "<latex>p_3</latex>"
== "no further progress with 0 running actors" ==
@enduml
