@startuml

'skinparam linetype polyline
skinparam nodesep 100
skinparam ranksep 100

state confirmed as "Confirmed" {
  state succeededEntirely as "Succeeded Entirely"
  state failFallible as "Fallible Failed"
  state failEntirely as "Failed Entirely"
}
state pending as "Pending"

state final as "Final" {
  state succeededEntirelyF as "Succeeded Entirely"
  state failFallibleF as "Fallible Failed"
  state failEntirelyF as "Failed Entirely"
}

state failed as "Failed"
state expected as "Expected"

[*] --> pending : spend
[*] --> confirmed : apply
[*] --> expected : watch_for
expected --> confirmed : apply
pending --> confirmed : apply
confirmed --> final : finalize
confirmed --> pending : rollback
pending ---> failed : discard
pending <-- final : rollback
confirmed --> failed : discard

@enduml
