@startuml

node "Node"

node "PubSub-Indexer" {
  portin WebSocketIn
  portout WebSocketOut
  portout HTTP
  database Index

  WebSocketIn -> [NodeClient]
  [NodeClient] --> [Indexer]
  [Indexer] --> Index
  [Indexer] --> [PubSub mechanism]
  [Subscription API] ----> WebSocketOut
  Index --> [PubSub mechanism]
  [PubSub mechanism] --> [Subscription API]
  Index --> [Query API]
  [Query API] ---> HTTP
}

Node --> WebSocketIn

node Wallet
WebSocketOut --> Wallet

node dApp
WebSocketOut --> dApp

node "Block Explorer" as explorer
HTTP --> explorer

@enduml
