@startuml overview
!function $crcName($name) !return $name + "CRC"
!procedure $crc($name, $responsibilities)
  component $crcName($name) as "
  |= Responsibilities |
  | $responsibilities |
  "
!endprocedure

together {
  actor dappUser as "dApp User"
  actor dappDeveloper as "dApp Developer"
}

together {
    frame dApp {
      artifact dAppCode as "dApp own code"

      component ClientSDK {
        $crc("ClientSDK", "run smart contracts\nprovide API for dApps")
        component laresRuntime as "Lares Runtime"
        artifact dAppConnectorClient as "dApp Connector Client"
        artifact abcirdProver as "Abcird Prover"
      }

      dAppCode -- ClientSDK
    }

    frame browserExtensionWallet as "Wallet Browser Extension" {
      $crc("browserExtensionWallet", "hold and protect keys\nscreate and send transactions\nexpose API for dApps")
      artifact dAppConnectorServer as "dApp Connector"
      artifact walletEngineJS as "Wallet Engine JS"
      artifact walletProver as "Wallet Prover"
    }
}

together {

    frame codeEditor as "Code Editor" {
      component editorPlugin as "Editor Plugin" {
        $crc("editorPlugin", "support for completions and syntax highligthing\nprovide integration with Midnight SDK for most common actions\nin-editor UI for most common actions")
        component syntaxHighlighting
        component testRunner
        component inEditorSimulator
      }
    }

    node midnightSDK as "Midnight SDK" {
      $crc("MidnightSDK", "Provide toolkit and libraries for dApp developer")
      component abcirdCompiler
      component abcirdLanguageServicer
      component midnightCLI
      artifact headlessWallet
      artifact mockNode
      artifact mockProver
    }

    editorPlugin -- midnightSDK
}

together {
    interface WalletAPI as "Wallet API"
    component walletEngine {
        $crc("walletEngine", "provide common building blocks for building Midnight wallets")
    }

    node walletBackend as "Wallet Backend" {
        $crc("walletBackend", "Pre-process transactions to:\n - save bandwith\n - save CPU\non user computers")
        artifact walletBackendEngine
    }

    WalletAPI ^.. walletEngine
    walletEngineJS -- walletBackend
    walletBackendEngine .^ walletEngine
}

together {
  component provingSystem as "Proving System" {
    $crc("provingSystem", "Generate and verify necessary zero-knowledge proofs")
  }
  node proofServer as "Proof Server"

  proofServer .u.^ provingSystem
}


together {
    node midnightNode as "Midnight Node" {
      $crc("midnightNode", "Run consensus\nevolve ledger")
      component midnightLedger
      component midnightConsensus
      component midnightAPI
    }

    node spoDeployment as "Cardano Node Installation" {
      node mainChainFollower as "Main Chain Follower" {
        $crc("mainChainFollower", "Provide Midnight information about\n  - stake distribution\n  - token transfers")
      }
      node cardanoNode as "Cardano Node"
    }

    midnightNode -- mainChainFollower
}

together {
  cloud midnightNetwork
  cloud cardanoNetwork
}



dappUser -- browserExtensionWallet
dappUser -- dApp
walletEngineJS ..^ walletEngine
walletBackend -- midnightNode
mainChainFollower -- cardanoNode
cardanoNode -- cardanoNetwork
walletEngineJS - walletProver
laresRuntime - abcirdProver
ClientSDK -- WalletAPI
midnightNode -- midnightNetwork

walletProver .u.^ provingSystem
abcirdProver .u.^ provingSystem

dappDeveloper -- midnightCLI
dappDeveloper -- codeEditor
headlessWallet ..^ walletEngine
mockNode ..^ midnightLedger
mockNode ..^ midnightAPI
mockProver ..^ provingSystem

package Legend {
  together {
    [A]
    [B]

    note top of A
      A component
    endnote
  }

  together {
    artifact C
    interface D

    note bottom of C
      An artifact
    endnote

    note bottom of D
      An interface
    endnote
  }
  A -[hidden]- C

  A - B : "A collaborates with B"
  C .^ D : "C is a specific version/implementation of D"
}

spoDeployment -[hidden]- Legend
@enduml
