@startuml
component ClientSDK
interface ClientSDKAPI
component DappClientCode
component dappConnectorClient
component StateManagement
component Prover
component Sync
component LaresRuntime

DappClientCode -- ClientSDKAPI : "uses"
ClientSDKAPI -- ClientSDK : "implemented by"

LaresRuntime .> StateManagement : "uses"
LaresRuntime .> Prover : "uses"
StateManagement <. Sync : "uses"
Sync ..> Prover : "uses"

ClientSDK -- dappConnectorClient : "embeds"
ClientSDK -- LaresRuntime : "embeds"
ClientSDK -- Sync : "embeds"
ClientSDK -- StateManagement : "embeds"
@enduml
